Global:
  pipeline_name: instance_segmentation
  input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_instance_segmentation_004.png
  
######################################## Setting ########################################
# Please select the model from bellow `Support`

Pipeline:
  model: Mask-RT-DETR-S

######################################## Support ########################################
NOTE:
  device: 
    - gpu
    - gpu:2
    - cpu
  batch_size: "任意正整数"
  model:
    - Mask-RT-DETR-S
