Global:
  pipeline_name: semantic_segmentation
  input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_image_classification_001.jpg
  
######################################## Setting ########################################
# Please select the model from bellow `Support`

Pipeline:
  model: PP-LiteSeg-T

######################################## Support ########################################
NOTE:
  device: 
    - gpu
    - gpu:2
    - cpu
  batch_size: "任意正整数"
  model:
    - PP-LiteSeg-T
