Global:
  model: LaTeX_OCR_rec
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "./dataset/ocr_rec_latexocr_dataset_example"
  device: gpu:0
  output: "output"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  epochs_iters: 20
  batch_size_train: 40
  batch_size_val: 10
  learning_rate: 0.0001
  pretrain_weight_path: null
  resume_path: null
  log_interval: 20
  eval_interval: 1
  save_interval: 1

Evaluate:
  weight_path: "output/best_accuracy.pdparams"
  log_interval: 1

Predict:
  model_dir: "output/best_accuracy"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_formula_rec_001.png"
  kernel_option:
    run_mode: paddle
    batch_size: 1